### PR TITLE
Updated README file

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
Added link to the License file in the Readme for easy access.

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@luciferreeves I have added a few more things in the Readme for it's enhancement. I have also fixed the error that you mentioned previously by fixing it with the correct link. Now, you can re-review this PR.

**Comment by SaptarshiSarkar12** [comment]
@luciferreeves please check why ci is failing, I think there is problem in that work flow file

**Comment by luciferreeves** [comment]
The workflow file seems fine. You might wanna look at [this line](https://github.com/luciferreeves/edify/actions/runs/3043826798/jobs/4912063340#step:5:25) - It says, `warning: check: Title underline too short. (line 158)`, which means exactly what it says. This is a problem with **_rst_** documents. You could look into the [Sphinx Documentation](https://www.sphinx-doc.org/en/master/usage/restructuredtext/index.html) for a fix though. Would you like me to help take care of this PR and fix the issues for you, or you want to do them yourself?

**Comment by SaptarshiSarkar12** [comment]
I am having less knowledge about rst files, so if you can fix this issue, then I request you to solve it. @luciferreeves

**Comment by luciferreeves** [comment]
Great, you can leave the PR open for now. I will push some more commits to refactor some things and then I will merge it.

**Comment by SaptarshiSarkar12** [comment]
Thanks @luciferreeves

**Comment by SaptarshiSarkar12** [comment]
> Great, you can leave the PR open for now. I will push some more commits to refactor some things and then I will merge it.

@luciferreeves How far is the work done?

**Comment by SaptarshiSarkar12** [comment]
@luciferreeves thank you for your cooperation.

**Pull request merged**
